version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./docker-entrypoint-init.sh:/usr/local/bin/docker-entrypoint-init.sh
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    entrypoint: ["/bin/bash", "-c", "/usr/local/bin/docker-entrypoint-init.sh && apache2-foreground"]

volumes:
  db_data: {}

